spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true



---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    username: sa
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;
    driver-class-name: org.h2.Driver
  freemarker:
    cache: false
  jpa:
    database: h2
  h2:
    console:
      enabled: true

